{{/*- define "magda.var_dump" -}}
{{- . | mustToPrettyJson | printf "\nThe JSON output of the dumped var is: \n%s" | fail }}
{{- end -}}
{{- template "magda.var_dump" $.Values */}}
{{- if not $.Values.secretName }}
{{- $db := $.Values.db }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ (printf "%s-secrets" (include "ahri.fullname" .)) }}
  labels:
    {{- include "ahri.labels" . | nindent 4 }}
type: Opaque
stringData:
  apiKey: {{ $.Values.apiKey | squote }}
  host: {{ $db.host | squote }}
  port: {{ $db.port | squote }}
  db: {{ $db.db | squote }}
  user: {{ $db.user | squote }}
  pass: {{ $db.pass | squote }}
{{- end }}
