name: Ahri pipeline

on:
  push:
    branches: [ $default-branch, ci ]

env:
  DATASET_URL: https://90victor09.ru/aiarch/News_Category_Dataset.json.zip
#  DATASET_URL: https://90victor09.ru/aiarch/News_Category_Dataset_v2.json.zip
#  DATASET_URL: https://90victor09.ru/aiarch/News_Category_Dataset_v3.json.zip
  MODELS: tfidf.SVCModel tfidf.KNNModel tfidf.MultinomialNBModel tfidf.RandomForestModel

jobs:
  dataset:
    runs-on: ubuntu-22.04

    steps:
      - name: cache source data
        id: cache-source-data
        uses: actions/cache@v3
        with:
          path: dataset.json
          key: source-dataset-${{ env.DATASET_URL }}

      - name: download source data
        if: steps.cache-source-data.outputs.cache-hit != 'true'
        run: |
          sudo apt-get install -y wget unzip
          wget -O dataset.zip $DATASET_URL
          unzip -p dataset.zip >dataset.json
          rm dataset.zip

      - name: Save source dataset
        uses: actions/upload-artifact@v3
        with:
          name: source-dataset
          path: ./dataset.json

  save-data:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/90victor09/ahri/base:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    needs: dataset
    environment: ahri

    steps:
      - uses: actions/checkout@v3

      - name: Download source dataset
        uses: actions/download-artifact@v3
        with:
          name: source-dataset
          path: ./

      - name: Prepare data
        run: |
          ln -s /root/nltk_data /github/home/nltk_data 
          ./prepare-data.py ./dataset.json ./output.json

      - name: Upload data
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_DB: ${{ secrets.DB_DB }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
        run: |
          ./save-data.py ./output.json

  train-models:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/90victor09/ahri/base:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    needs: save-data
    environment: ahri

    strategy:
      fail-fast: false
      matrix:
        model:
          - tfidf.SVCModel
          - tfidf.KNNModel
          - tfidf.MultinomialNBModel
          - tfidf.RandomForestModel

    steps:
      - uses: actions/checkout@v3

      - name: Train model ${{ matrix.model }}
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_DB: ${{ secrets.DB_DB }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
        run: |
          ./train-model.py ${{ matrix.model }}

  select-model:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/90victor09/ahri/base:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    needs: train-models
    environment: ahri

    steps:
      - uses: actions/checkout@v3

      - name: Select model
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_DB: ${{ secrets.DB_DB }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
        run: |
          ./select-model.py ${{ env.MODELS }}
